name:                monkeyInterpreter
version:             0.1.0.0
github:              "kunihiko-t/monkey-interpreter-haskell"
license:             BSD3
author:              "Kunihiko Tanaka"
maintainer:          "inverse.of.void.matrix@gmail.com"
copyright:           "2019 Kunihiko Tanaka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kunihiko-t/monkey-interpreter-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- lens

library:
  source-dirs: src

executables:
  monkey-interpreter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monkeyInterpreter

tests:
  testProject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monkeyInterpreter
